### ISSUE TITLE
Using Elastic Search on Heroku

### ISSUE THREAD

**Issue by kaustubhkabra** [vinsol/shopspree-sales-app#60]
Hi,
I deployed the app here : http://agile-citadel-81006.herokuapp.com/. However, I am unable to configure source code to use Bonsai/any other plugin for elastic search in Heroku as such GET api/ams/products fail with connection error. I tried this code but do not think Elasticsearch's client is getting updated -
```
   if ENV['BONSAI_URL']
        logs.d
        Elasticsearch::Model.client = Elasticsearch::Client.new({url: ENV['BONSAI_URL'], logs: true})
        BONSAI_INDEX_NAME = ENV['BONSAI_URL'][/[^\/]+$/]
    else
        app_name = Rails.application.class.parent_name.underscore.dasherize
        BONSAI_INDEX_NAME = "#{app_name}-#{Rails.env}"
    end
```

Can you please point to any direction ? I just want GET /products to work.

**Comment by nimish-mehta** [comment]
@kaustubh-kabra You need to set the bonsai url here: https://github.com/vinsol-spree-contrib/shopspree-sales-app/blob/master/config/initializers/chewy.rb and run ```rake chewy:reset``` to set up the index.

**Comment by kaustubhkabra** [comment]
Thanks @nimish-mehta. My "spree" index was previous created (most probably when I ran sandbox app from https://github.com/spree/spree). I deleted spree index and then I ran` rake chewy:reset `to build the index but it is not getting created. Thoughts ?

**Comment by kaustubhkabra** [comment]
@nimish-mehta @pikender Any help on above comment ?

**Comment by nghiapdx** [comment]
@kaustubh-kabra, add-ons SearchBox Elasticsearch should work. must remove Bonsai.

**Comment by kaustubh-kabra** [comment]
@nghiapdx I did that. Running on EC2 instance now so no external Elastic Search implementation needed. Still, I am unable to recreate index.

**Comment by kaustubh-kabra** [comment]
I don't know what changed but running same command today worked fine and I got the index created.

**rake chewy:reset** 
```
Resetting SpreeIndex
  Imported SpreeIndex::Product for 0.46s, documents total: 16
  Imported SpreeIndex::Taxon for 0.06s, documents total: 11

```
I am still not sure what changed.

**Comment by kaustubhkabra** [comment]
I made project changes to make it work.
